workers_dev = true
name = "drink-elixir"
compatibility_date = "2024-11-18"
main = "./worker.ts"
assets = { directory = "./build/client" }

[vars]


[[d1_databases]]
binding = "DB"
database_name = "drink-elixir"
database_id = "1739e129-7fb2-4ba9-8ec0-3141e7dd3a64"
