workers_dev = true
name = "drink-elixir"
compatibility_date = "2024-11-18"
main = "./worker.ts"
assets = { directory = "./build/client" }

[vars]


[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "1"
